typedef struct {
	char *name;
	int type;
	char pad0[52];
	struct RecvTable *table;
	int offset;
	char pad1[16];
} RecvProp;

typedef struct RecvTable {
	RecvProp *props;
	int count;
	char pad0[8];
	char *name;
	char pad1[2];
} RecvTable;

typedef enum {
	CLASSID_BASECSGRENADEPROJECTILE = 9,
	CLASSID_BREACHCHARGEPROJECTILE = 29,
	CLASSID_BUMPMINEPROJECTILE = 33,
	CLASSID_C4,
	CLASSID_CHICKEN = 36,
	CLASSID_CSPLAYER = 40,
	CLASSID_CSPLAYERRESOURCE,
	CLASSID_CSRAGDOLL = 42,
	CLASSID_DEAGLE = 46,
	CLASSID_DECOYPROJECTILE = 48,
	CLASSID_DRONE,
	CLASSID_DRONEGUN,
	CLASSID_DYNAMICPROP = 52,
	CLASSID_ECONENTITY = 53,
	CLASSID_ECONWEARABLE,
	CLASSID_HOSTAGE = 97,
	CLASSID_INFERNO = 100,
	CLASSID_HEALTHSHOT = 104,
	CLASSID_CASH,
	CLASSID_KNIFE = 107,
	CLASSID_KNIFEGG,
	CLASSID_MOLOTOVPROJECTILE = 114,
	CLASSID_AMMOBOX = 125,
	CLASSID_LOOTCRATE,
	CLASSID_RADARJAMMER,
	CLASSID_WEAPONUPGRADE,
	CLASSID_PLANTEDC4,
	CLASSID_PROPDOORROTATING = 143,
	CLASSID_SENSORGRENADEPROJECTILE = 153,
	CLASSID_SMOKEGRENADEPROJECTILE = 157,
	CLASSID_SNOWBALLPILE = 160,
	CLASSID_SNOWBALLPROJECTILE,
	CLASSID_TABLET = 172,
	CLASSID_AUG = 232,
	CLASSID_AWP,
	CLASSID_ELITE = 239,
	CLASSID_FIVESEVEN = 241,
	CLASSID_G3SG1,
	CLASSID_GLOCK = 245,
	CLASSID_P2000,
	CLASSID_P250 = 258,
	CLASSID_SCAR20 = 261,
	CLASSID_SG553 = 265,
	CLASSID_SSG08 = 267,
	CLASSID_TEC9 = 269
} ClassId;

typedef struct ClientClass {
	char pad0[16];
	char *name;
	RecvTable *table;
	struct ClientClass *next;
	ClassId classid;
} ClientClass;

ClientClass *getallclasses(void);
