#ifndef FRAMESTAGE_H_
#define FRAMESTAGE_H_

typedef enum {
	FS_UNDEFINED = -1,
	FS_START,
	FS_NET_UPDATE_START,
	FS_NET_UPDATE_POSTDATAUPDATE_START,
	FS_NET_UPDATE_POSTDATAUPDATE_END,
	FS_NET_UPDATE_END,
	FS_RENDER_START,
	FS_RENDER_END
} FrameStage;

#endif /* FRAMESTAGE_H_ */
